version: '3.7'
services:
  main_todolist_db:
    image: postgres:12.0-alpine
    volumes:
      - todolist_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todolist
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432

volumes:
  todolist_postgres_data: